### PR TITLE
show "from" even when "to" is not selected in <DatePickerInput>

### PR DESCRIPTION
**Pull request by mehrad77**
Screenshot from 2019-06-05 16-35-51

### CODE REVIEW

**Comment by Kiarash-Z** [comment]
Hello Mehrad,
Can you provide a description of the changes you've made please?

**Comment by mehrad77** [comment]
So previously when we wanted to select a date range, the input text only would update when both `from` and `to` was selected. I thought that it can be better (UX Perspective) to show input text even if only `from` is selected. the screenshot is provided in the first comment.

**Comment by Kiarash-Z** [comment]
@mehrad77 Thanks for the provided description. I think this would result in conflicts with `formatInputText`. What do you think? 🤔

**Comment by mehrad77** [comment]
actually, you're right and this also can be done with `formatInputText` prop (that I wasn't aware of at the time). but still, I think it's a better approach for showing default input text but its not necessary at all.

you can close the pull request if you think it's not better.

**Comment by Kiarash-Z** [comment]
I think it's better to close this PR. This feature can be easily implemented by any client. I appreciate your efforts and contributions though. Thank you Mehrad ❤️

**Pull request closed without merging**
